version: '3.8'

services:
  api: 
    build: ./server
    container_name: server-chat
    ports:
      - '4000:4000'
    volumes:
      - ./server:/app
      - ./app/node_modules
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - ./app/node_modules
    stdin_open: true
    tty: true  